# Numpy

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.46489157, 0.6410985 , 0.96247232, 0.16795933, 0.1825381 ])

In [15]:
np.random.randn(4,4)

array([[ 1.3554907 , -0.46206987, -1.16482346,  0.93049397],
       [-0.46380971,  0.86133857, -0.09527486, -0.187136  ],
       [-1.26188048, -1.54117007,  0.58530529,  0.44801725],
       [ 0.46876134,  0.85485081, -0.91825927, -0.31295187]])

In [16]:
np.random.randint(1,100,10)

array([45, 20, 35, 16, 40, 26, 96, 26, 36,  8])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
ranarr

array([45, 31, 44, 29, 30, 49, 32, 43, 30, 35])

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ranarr

array([45, 31, 44, 29, 30, 49, 32, 43, 30, 35])

In [23]:
ranarr.max()

49

In [24]:
ranarr.min()

29

In [25]:
ranarr.argmax()

5

In [26]:
ranarr.argmin()

3

In [27]:
arr.shape

(25,)

In [30]:
arr = arr.reshape(5,5)

In [31]:
arr.shape

(5, 5)

In [33]:
arr.dtype

dtype('int64')

In [34]:
from numpy.random import randint

In [35]:
randint(2,10)

5